//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hardvin_demo_web_worker_role_service_bus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaGeneracion { get; set; }
    }
}
